//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.04 at 03:17:23 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://icellmobilsoft.hu/pattern/validation/test/dto", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.icellmobilsoft.xsd.pattern.validation.test.dto;
